export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST';
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS';
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL';

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST';
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS';
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL';


export const ORDER_MINE_LIST_REQUEST = 'ORDER_MINE_LIST_REQUEST';
export const ORDER_MINE_LIST_SUCCESS = 'ORDER_MINE_LIST_SUCCESS';
export const ORDER_MINE_LIST_FAIL = 'ORDER_MINE_LIST_FAIL';

export const ORDER_APPROVE_REQUEST = 'ORDER_APPROVE_REQUEST';
export const ORDER_APPROVE_SUCCESS = 'ORDER_APPROVE_SUCCESS';
export const ORDER_APPROVE_FAIL = 'ORDER_APPROVE_FAIL';


export const GET_ORDER_BY_STATUS_REQUEST = 'GET_ORDER_BY_STATUS_REQUEST';
export const GET_ORDER_BY_STATUS_SUCCESS = 'GET_ORDER_BY_STATUS_SUCCESS';
export const GET_ORDER_BY_STATUS_FAIL = 'GET_ORDER_BY_STATUS_FAIL';

export const SEND_MAIL_ORDER_REQUEST = "SEND_MAIL_ORDER_REQUEST";
export const SEND_MAIL_ORDER_SUCCESS = "SEND_MAIL_ORDER_SUCCESS";


export const ORDER_PAYMENT_METHOD = 'ORDER_PAYMENT_METHOD';

