export const PUBLISHER_LIST_REQUEST = 'PUBLISHER_LIST_REQUEST'
export const PUBLISHER_LIST_SUCCESS = 'PUBLISHER_LIST_SUCCESS'
export const PUBLISHER_LIST_FAIL = 'PUBLISHER_LIST_FAIL'

export const PUBLISHER_DETAILS_REQUEST = 'PUBLISHER_DETAILS_REQUEST'
export const PUBLISHER_DETAILS_SUCCESS = 'PUBLISHER_DETAILS_SUCCESS'
export const PUBLISHER_DETAILS_FAIL = 'PUBLISHER_DETAILS_FAIL'

export const PUBLISHER_DELETE_REQUEST = 'PUBLISHER_DELETE_REQUEST'
export const PUBLISHER_DELETE_SUCCESS = 'PUBLISHER_DELETE_SUCCESS'
export const PUBLISHER_DELETE_FAIL = 'PUBLISHER_DELETE_FAIL'
export const PUBLISHER_DELETE_RESET = 'PUBLISHER_DELETE_RESET'

export const PUBLISHER_CREATE_REQUEST = 'PUBLISHER_CREATE_REQUEST'
export const PUBLISHER_CREATE_SUCCESS = 'PUBLISHER_CREATE_SUCCESS'
export const PUBLISHER_CREATE_FAIL = 'PUBLISHER_CREATE_FAIL'
export const PUBLISHER_CREATE_RESET = 'PUBLISHER_CREATE_RESET'

export const PUBLISHER_UPDATE_REQUEST = 'PUBLISHER_UPDATE_REQUEST'
export const PUBLISHER_UPDATE_SUCCESS = 'PUBLISHER_UPDATE_SUCCESS'
export const PUBLISHER_UPDATE_FAIL = 'PUBLISHER_UPDATE_FAIL'
export const PUBLISHER_UPDATE_RESET = 'PUBLISHER_UPDATE_RESET'

export const PUBLISHER_RESET = 'PUBLISHER_RESET';
